{
 "title": "Docker Swarm Service and Container Metrics",
 "description": "Docker swarm services and container metrics via Google Cadvisor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_memory_usage_bytes, job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "query_result(count(container_last_seen{container_label_com_docker_stack_namespace=~\".+\", instance=~\"$host\"}) by (container_label_com_docker_stack_namespace))"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "query_result(count(container_last_seen{container_label_com_docker_swarm_service_name=~\".+\", instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\"}) by (container_label_com_docker_swarm_service_name))"
    }
   },
   {
    "name": "cont",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{job=~\"$job\", image!=\"\", instance=~\"$host\"}, name)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "linx-integration, sap-integration, server"
   }
  ]
 },
 "panels": [
  { "title": "Service stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by service per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval])) by (container_label_com_docker_swarm_service_name) * 100 ",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory usage by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}) by (container_label_com_docker_swarm_service_name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net IO by  service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}\r\n[$__rate_interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "rx {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}\r\n[$__rate_interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "tx {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Disk IO by service",
   "type": "timeseries",
   "description": "Permite identificar quais serviços estão a gerar mais carga sobre o disco, o que pode ser útil para:\n\n- Diagnóstico de gargalos: Identificar se um serviço está a ter problemas de desempenho devido a um grande volume de operações de E/S.\n- Otimização: Ajustar a configuração do sistema para melhorar a performance de serviços que são muito exigentes em E/S.\n- Monitorização: Controlar a utilização do disco pelos serviços e identificar tendências de utilização. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "read {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "-sum (rate(container_fs_writes_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "write {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Containers per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(container_last_seen{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
    }
   ]
  },
  { "title": "Container stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage by container per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\",name=~\"$cont\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\",name=~\"$cont\",image!=\"\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net IO by container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\",name=~\"$cont\"}\r\n[$__rate_interval])) by (name)",
     "legendFormat": "rx {{name}}"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\",name=~\"$cont\"}\r\n[$__rate_interval])) by (name)",
     "legendFormat": "tx {{name}}"
    }
   ]
  },
  {
   "title": "Disk IO by  container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\",name=~\"$cont\"}[$__rate_interval])) by (name)",
     "legendFormat": "read {{name}}"
    },
    {
     "expr": "-sum by (name) (rate(container_fs_writes_bytes_total{job=~\"$job\",instance=~\"$host\",container_label_com_docker_stack_namespace=~\"$stack\", container_label_com_docker_swarm_service_name=~\"$service\",name=~\"$cont\"}[$__rate_interval]))",
     "legendFormat": "write {{name}}"
    }
   ]
  },
  {
   "title": "Containers Created",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}