global:
  resolve_timeout: 5m

receivers:
  - name: 'default-receiver'
route:
  group_interval: 5m
  group_wait: 30s
  receiver: 'default-receiver'
  repeat_interval: 24h

# global:
#   slack_api_url: 'https://hooks.slack.com/servicesE'
#   resolve_timeout: 5m

# route:
#   receiver: 'slack-notifications'
#   group_by: ['alertname', 'instance']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1h

# receivers:
#   - name: 'slack-notifications'
#     slack_configs:
#       - channel: '#alerts'
#         send_resolved: true
#         icon_emoji: ':warning:'
#         title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
#         text: "{{ range .Alerts }}*Alerta:* {{ .Labels.alertname }}\n*Resumo:* {{ .Annotations.summary }}\n*Descrição:* {{ .Annotations.description }}\n*Severidade:* {{ .Labels.severity }}\n*Instance:* {{ .Labels.instance }}\n*Início:* {{ .StartsAt }}{{ if eq .Status \"resolved\" }}\n*Resolvido:* {{ .EndsAt }}{{ end }}\n\n{{ end }}"